export const GET_CHANNELS = 'GET_CHANNELS';
export const SORT_CHANNELS = 'SORT_CHANNELS';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';
